
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/editor-ldm
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=default-user
quarkus.datasource.password=default-password
quarkus.datasource.reactive=false
quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=SELECT u.password, u.role FROM "concevoir_pri".utilisateur u WHERE u.username=?
quarkus.security.jdbc.principal-query.clear-password-mapper.enabled=true
quarkus.security.jdbc.principal-query.clear-password-mapper.password-index=1
quarkus.security.jdbc.principal-query.attribute-mappings.0.index=2
quarkus.security.jdbc.principal-query.attribute-mappings.0.to=groups
quarkus.http.ssl.certificate.files=temp.p12.crt
quarkus.http.ssl.certificate.key-files=temp.p12.key
quarkus.http.insecure-requests=redirect
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.http.test-port=8081
#On ne peut pas mettre 443 vertx probleme
quarkus.http.ssl-port=8443
quarkus.http.test-ssl-port=8444
quarkus.http.cors=true
quarkus.http.cors.origins=https://localhost:8443,http://localhost:9001,https://diamant.dinf.fsci.usherbrooke.ca:8443
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=OPTIONS, POST, GET
quarkus.http.http2=false
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
